device: 'cuda:1'

tokenizer:
    path: '../input/tokenizer'
    file: 'tokenizer'

images:
    size: 256

dataframes:
    path: '../input/dataframes/'
    file: 'test.csv'
    num_workers: 8

model:
    backbone: 'resnet34'
    level: -1
    hidden_size: 128
    num_hidden_layers: 6
    num_attention_heads: 8
    max_len: 200

predict:
    batch_size: 1024
    model_path: 'logs/checkpoints/best_full.pth'
    score: True
    path: '../predicts/'
    file: 'predict_test.csv'
    