seed: 42
device: 'cuda:2'

tokenizer:
    path: '../input/tokenizer'
    file: 'tokenizer'

images:
    size: 256

dataframes:
    path: '../input/dataframes/'
    num_workers: 8

model:
    backbone: 'resnet34'
    level: -1
    emb_dim: 128
    
training:
    batch_size: 80
    lr: 5e-4
    T_max: 10
    num_epochs: 50
    logdir: './logs'
    resume: 'logs/checkpoints/last_full.pth'
    